// <auto-generated />
using System;
using LowcodeAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LowcodeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102193347_AddAppPagesTable")]
    partial class AddAppPagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LowcodeAPI.Domain.Entities.AppPackage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AppCredential")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AppDesc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AppVersion")
                        .HasColumnType("integer");

                    b.Property<string>("App_Settings")
                        .HasColumnType("jsonb");

                    b.Property<int>("CreateBy")
                        .HasColumnType("integer");

                    b.Property<int>("CreateMethod")
                        .HasColumnType("integer");

                    b.Property<string>("CreateSource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DeployMeta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeploySetting")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExportSetting")
                        .HasColumnType("jsonb");

                    b.Property<string>("Maintenance_Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Maintenance_Status")
                        .HasColumnType("integer");

                    b.Property<string>("Maintenance_Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PageLayout")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("jsonb");

                    b.Property<string>("Thumnail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ViewTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppCredential");

                    b.HasIndex("CreateBy");

                    b.HasIndex("Uuid");

                    b.ToTable("app_package", (string)null);
                });

            modelBuilder.Entity("LowcodeAPI.Domain.Entities.AppPage", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("page_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PageId"));

                    b.Property<int>("AllowPageAvatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("allowPageAvatar");

                    b.Property<short>("AutoPlaySec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("auto_play_sec");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("bgcolor");

                    b.Property<short>("CanvasType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("canvastype");

                    b.Property<short>("CollapseExpandObjectsStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("collapse_expand_objects_status");

                    b.Property<int>("CountNumAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count_num_access");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DeepUiMetaData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("deep_ui_meta_data")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<short>("DisplayStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("display_status");

                    b.Property<short>("DocFlowType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("docflowtype");

                    b.Property<short>("DocPerCol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("docpercol");

                    b.Property<short>("DocPerRow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("docperrow");

                    b.Property<string>("DynamicBinding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("dynamic_binding")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("EnableDoubleClickToViewImageWidgets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("enableDoubleClickToViewImageWidgets");

                    b.Property<int?>("EnablePageCache")
                        .HasColumnType("integer")
                        .HasColumnName("enablePageCache");

                    b.Property<short>("EnablePasteConfirmation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("enablePasteConfirmation");

                    b.Property<int>("ExpirationTime")
                        .HasColumnType("integer")
                        .HasColumnName("expiration_time");

                    b.Property<int?>("GeoZoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("geozoom");

                    b.Property<short>("IRatio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("iratio");

                    b.Property<short>("IsTwoColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5)
                        .HasColumnName("istwocolumn");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastaccess");

                    b.Property<double>("Lat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("lat");

                    b.Property<string>("LayoutSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_settings");

                    b.Property<double>("Lng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("lng");

                    b.Property<short>("LockUnlockObjectsStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("lock_unlock_objects_status");

                    b.Property<int>("MaxNumAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_num_access");

                    b.Property<string>("ObjectEventBinding")
                        .HasColumnType("jsonb")
                        .HasColumnName("object_event_binding");

                    b.Property<double>("ObjectsCacheTimeout")
                        .HasColumnType("double precision")
                        .HasColumnName("objects_cache_timeout");

                    b.Property<double>("ObjectsCacheTimeoutMeta")
                        .HasColumnType("double precision")
                        .HasColumnName("objects_cache_timeout_meta");

                    b.Property<short>("POrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("porder");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("character varying(550)")
                        .HasColumnName("pagename");

                    b.Property<short>("PageNotShareInBindle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("pageNotShareInBindle");

                    b.Property<string>("Password")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("password");

                    b.Property<short>("Publish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("publish");

                    b.Property<short>("Recommend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("recommend");

                    b.Property<short>("ReportNumPages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("report_num_pages");

                    b.Property<string>("SecuritySettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("security_settings");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("thumbnail");

                    b.Property<int?>("ThumbnailMask")
                        .HasColumnType("integer")
                        .HasColumnName("thumbnailmask");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<short>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("visibility");

                    b.Property<float>("WidthCol0")
                        .HasColumnType("real")
                        .HasColumnName("width_col0");

                    b.Property<float>("WidthCol1")
                        .HasColumnType("real")
                        .HasColumnName("width_col1");

                    b.Property<float>("WidthCol2")
                        .HasColumnType("real")
                        .HasColumnName("width_col2");

                    b.Property<float>("WidthCol3")
                        .HasColumnType("real")
                        .HasColumnName("width_col3");

                    b.Property<float>("WidthCol4")
                        .HasColumnType("real")
                        .HasColumnName("width_col4");

                    b.Property<short>("Zoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("zoom");

                    b.HasKey("PageId");

                    b.HasIndex("DisplayStatus");

                    b.HasIndex("PageName");

                    b.HasIndex("Publish");

                    b.HasIndex("UserId");

                    b.ToTable("app_pages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
