// <auto-generated />
using System;
using LowcodeAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LowcodeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102164855_CreateAppPackage")]
    partial class CreateAppPackage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LowcodeAPI.Domain.Entities.AppPackage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AppCredential")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AppDesc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AppVersion")
                        .HasColumnType("integer");

                    b.Property<string>("App_Settings")
                        .HasColumnType("jsonb");

                    b.Property<int>("CreateBy")
                        .HasColumnType("integer");

                    b.Property<int>("CreateMethod")
                        .HasColumnType("integer");

                    b.Property<string>("CreateSource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeployMeta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeploySetting")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExportSetting")
                        .HasColumnType("jsonb");

                    b.Property<string>("Maintenance_Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Maintenance_Status")
                        .HasColumnType("integer");

                    b.Property<string>("Maintenance_Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PageLayout")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("jsonb");

                    b.Property<string>("Thumnail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ViewTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppCredential");

                    b.HasIndex("CreateBy");

                    b.HasIndex("Uuid");

                    b.ToTable("app_package", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
